<a href="https://colab.research.google.com/github/gautam200/demo/blob/main/K_Nearest_Neighbour.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**K Nearest Neighbours **

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**KNeighbors Classifier**

In [ ]:
import pandas as pd                                       #data manipulation
import numpy as np                                        #data manipulation
import sklearn                                            #ML support
from sklearn.neighbors import KNeighborsClassifier as knn #KNN Classifier


In [ ]:
df = pd.read_csv("knn.csv")                             #Loading the data into data frame
df

X  Y Class
0  2  4     N
1  4  6     N
2  4  4     P
3  4  2     N
4  6  4     N
5  6  2     P

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:,2].values

In [ ]:
x

array([[2, 4],
       [4, 6],
       [4, 4],
       [4, 2],
       [6, 4],
       [6, 2]])

In [ ]:
y

array(['N', 'N', 'P', 'N', 'N', 'P'], dtype=object)

In [ ]:
classifier = knn(n_neighbors=3)         #creating a knn model

In [ ]:
classifier.fit(x,y)                     #training the data

KNeighborsClassifier(n_neighbors=3)

In [ ]:
x_test= np.array([7,6])
y_predict = classifier.predict([x_test])        #predicting using model

In [ ]:
y_predict

array(['N'], dtype=object)

**KNN Activity |  as k increase accuracy decrease**

**KNeighbors Regressor**

In [ ]:
from sklearn.neighbors import KNeighborsRegressor as knn1
df = pd.read_csv("knn1.csv")

In [ ]:
df

Height  Age  Weight
0    5.00   45      77
1    5.11   26      47
2    5.60   30      55
3    5.90   34      59
4    4.80   40      72
5    5.80   36      60
6    5.30   19      40
7    5.80   28      60
8    5.50   23      45
9    5.60   32      58

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:,2].values

In [ ]:
x

array([[ 5.  , 45.  ],
       [ 5.11, 26.  ],
       [ 5.6 , 30.  ],
       [ 5.9 , 34.  ],
       [ 4.8 , 40.  ],
       [ 5.8 , 36.  ],
       [ 5.3 , 19.  ],
       [ 5.8 , 28.  ],
       [ 5.5 , 23.  ],
       [ 5.6 , 32.  ]])

In [ ]:
y

array([77, 47, 55, 59, 72, 60, 40, 60, 45, 58])

In [ ]:
classifier = knn1(n_neighbors= 3)

In [ ]:
classifier.fit(x,y)

KNeighborsRegressor(n_neighbors=3)

In [ ]:
x_test= np.array([4.5,36])
y_predict = classifier.predict([x_test])        #predicting using model

In [ ]:
y_predict

array([63.66666667])

In [ ]:
classifier = knn1(n_neighbors= 4)

In [ ]:
classifier.fit(x,y)

KNeighborsRegressor(n_neighbors=4)

In [ ]:
x_test= np.array([4.5,36])
y_predict = classifier.predict([x_test])        #predicting using model

In [ ]:
y_predict

array([62.25])

**Heart .csv file  (classifier)**

In [ ]:
df = pd.read_csv("heart.csv")                             #Loading the data into data frame
df

age  sex  chest_pain_type  resting_bp  cholestoral  fasting_blood_sugar  \
0     63    1                3         145          233                    1   
1     37    1                2         130          250                    0   
2     41    0                1         130          204                    0   
3     56    1                1         120          236                    0   
4     57    0                0         120          354                    0   
..   ...  ...              ...         ...          ...                  ...   
298   57    0                0         140          241                    0   
299   45    1                3         110          264                    0   
300   68    1                0         144          193                    1   
301   57    1                0         130          131                    0   
302   57    0                1         130          236                    0   

     restecg  max_hr  exang  oldpeak  slope  num_major_vessels  thal  target  
0          0     150      0      2.3      0                  0     1       1  
1          1     187      0      3.5      0                  0     2       1  
2          0     172      0      1.4      2                  0     2       1  
3          1     178      0      0.8      2                  0     2       1  
4          1     163      1      0.6      2                  0     2       1  
..       ...     ...    ...      ...    ...                ...   ...     ...  
298        1     123      1      0.2      1                  0     3       0  
299        1     132      0      1.2      1                  0     3       0  
300        1     141      0      3.4      1                  2     3       0  
301        1     115      1      1.2      1                  1     3       0  
302        0     174      0      0.0      1                  1     2       0  

[303 rows x 14 columns]

In [ ]:
x = df.iloc[:,:2].values
y = df.iloc[:,13].values

In [ ]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
x

array([[63,  1],
       [37,  1],
       [41,  0],
       [56,  1],
       [57,  0],
       [57,  1],
       [56,  0],
       [44,  1],
       [52,  1],
       [57,  1],
       [54,  1],
       [48,  0],
       [49,  1],
       [64,  1],
       [58,  0],
       [50,  0],
       [58,  0],
       [66,  0],
       [43,  1],
       [69,  0],
       [59,  1],
       [44,  1],
       [42,  1],
       [61,  1],
       [40,  1],
       [71,  0],
       [59,  1],
       [51,  1],
       [65,  0],
       [53,  1],
       [41,  0],
       [65,  1],
       [44,  1],
       [54,  1],
       [51,  1],
       [46,  0],
       [54,  0],
       [54,  1],
       [65,  0],
       [65,  0],
       [51,  0],
       [48,  1],
       [45,  1],
       [53,  0],
       [39,  1],
       [52,  1],
       [44,  1],
       [47,  1],
       [53,  0],
       [53,  0],
       [51,  0],
       [66,  1],
       [62,  1],
       [44,  0],
       [63,  0],
       [52,  1],
       [48,  1],
       [45,  1],
       [34,  1

In [ ]:
classifier = knn(n_neighbors=4)         #creating a knn model

In [ ]:
classifier.fit(x,y)                     #training the data

KNeighborsClassifier(n_neighbors=4)

In [ ]:
x_test= np.array([8,9])
y_predict = classifier.predict([x_test])        #predicting using model

In [ ]:
y_predict

array([1])

In [ ]:
#normalization
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(df[['cholestoral']].values.astype(float))
df['chol_normalized2']=x_scaled
df[['cholestoral','chol_normalized2']]

cholestoral  chol_normalized2
0            233          0.244292
1            250          0.283105
2            204          0.178082
3            236          0.251142
4            354          0.520548
..           ...               ...
298          241          0.262557
299          264          0.315068
300          193          0.152968
301          131          0.011416
302          236          0.251142

[303 rows x 2 columns]

In [ ]:
df.isnull().sum()

age                    0
sex                    0
chest_pain_type        0
resting_bp             0
cholestoral            0
fasting_blood_sugar    0
restecg                0
max_hr                 0
exang                  0
oldpeak                0
slope                  0
num_major_vessels      0
thal                   0
target                 0
normalized2            0
dtype: int64

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

scaler = MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(df[['age']].values.astype(float))
df['age_normalized_data']=x_scaled
df[['age','age_normalized_data']]

age  age_normalized_data
0     63             0.708333
1     37             0.166667
2     41             0.250000
3     56             0.562500
4     57             0.583333
..   ...                  ...
298   57             0.583333
299   45             0.333333
300   68             0.812500
301   57             0.583333
302   57             0.583333

[303 rows x 2 columns]

In [ ]:
scaler = MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(df[['resting_bp']].values.astype(float))
df['resting_bp_normalized_data1']=x_scaled
df[['resting_bp','resting_bp_normalized_data1']]


resting_bp  resting_bp_normalized_data1
0           145                     0.481132
1           130                     0.339623
2           130                     0.339623
3           120                     0.245283
4           120                     0.245283
..          ...                          ...
298         140                     0.433962
299         110                     0.150943
300         144                     0.471698
301         130                     0.339623
302         130                     0.339623

[303 rows x 2 columns]

In [ ]:
X = df.drop(columns = ["resting_bp",'cholestoral','age'])

In [ ]:
X

sex  chest_pain_type  fasting_blood_sugar  restecg  max_hr  exang  \
0      1                3                    1        0     150      0   
1      1                2                    0        1     187      0   
2      0                1                    0        0     172      0   
3      1                1                    0        1     178      0   
4      0                0                    0        1     163      1   
..   ...              ...                  ...      ...     ...    ...   
298    0                0                    0        1     123      1   
299    1                3                    0        1     132      0   
300    1                0                    1        1     141      0   
301    1                0                    0        1     115      1   
302    0                1                    0        0     174      0   

     oldpeak  slope  num_major_vessels  thal  target  normalized2  \
0        2.3      0                  0     1       1     0.244292   
1        3.5      0                  0     2       1     0.283105   
2        1.4      2                  0     2       1     0.178082   
3        0.8      2                  0     2       1     0.251142   
4        0.6      2                  0     2       1     0.520548   
..       ...    ...                ...   ...     ...          ...   
298      0.2      1                  0     3       0     0.262557   
299      1.2      1                  0     3       0     0.315068   
300      3.4      1                  2     3       0     0.152968   
301      1.2      1                  1     3       0     0.011416   
302      0.0      1                  1     2       0     0.251142   

     normalized_data  normalized_data1  resting_bp_normalized_data1  \
0           0.708333          0.481132                     0.481132   
1           0.166667          0.339623                     0.339623   
2           0.250000          0.339623                     0.339623   
3           0.562500          0.245283                     0.245283   
4           0.583333          0.245283                     0.245283   
..               ...               ...                          ...   
298         0.583333          0.433962                     0.433962   
299         0.333333          0.150943                     0.150943   
300         0.812500          0.471698                     0.471698   
301         0.583333          0.339623                     0.339623   
302         0.583333          0.339623                     0.339623   

     age_normalized_data  chol_normalized2  
0               0.708333          0.244292  
1               0.166667          0.283105  
2               0.250000          0.178082  
3               0.562500          0.251142  
4               0.583333          0.520548  
..                   ...               ...  
298             0.583333          0.262557  
299             0.333333          0.315068  
300             0.812500          0.152968  
301             0.583333          0.011416  
302             0.583333          0.251142  

[303 rows x 17 columns]

In [ ]:
X = df.drop(columns = ["normalized2",'normalized_data','normalized_data1',"resting_bp",'cholestoral','age'])

In [ ]:
X

sex  chest_pain_type  fasting_blood_sugar  restecg  max_hr  exang  \
0      1                3                    1        0     150      0   
1      1                2                    0        1     187      0   
2      0                1                    0        0     172      0   
3      1                1                    0        1     178      0   
4      0                0                    0        1     163      1   
..   ...              ...                  ...      ...     ...    ...   
298    0                0                    0        1     123      1   
299    1                3                    0        1     132      0   
300    1                0                    1        1     141      0   
301    1                0                    0        1     115      1   
302    0                1                    0        0     174      0   

     oldpeak  slope  num_major_vessels  thal  target  \
0        2.3      0                  0     1       1   
1        3.5      0                  0     2       1   
2        1.4      2                  0     2       1   
3        0.8      2                  0     2       1   
4        0.6      2                  0     2       1   
..       ...    ...                ...   ...     ...   
298      0.2      1                  0     3       0   
299      1.2      1                  0     3       0   
300      3.4      1                  2     3       0   
301      1.2      1                  1     3       0   
302      0.0      1                  1     2       0   

     resting_bp_normalized_data1  age_normalized_data  chol_normalized2  
0                       0.481132             0.708333          0.244292  
1                       0.339623             0.166667          0.283105  
2                       0.339623             0.250000          0.178082  
3                       0.245283             0.562500          0.251142  
4                       0.245283             0.583333          0.520548  
..                           ...                  ...               ...  
298                     0.433962             0.583333          0.262557  
299                     0.150943             0.333333          0.315068  
300                     0.471698             0.812500          0.152968  
301                     0.339623             0.583333          0.011416  
302                     0.339623             0.583333          0.251142  

[303 rows x 14 columns]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.3,random_state=42)

In [ ]:
len(x_train),len(x_test),len(y_train),len(y_test)

(90, 213, 90, 213)

In [ ]:
x_train

array([[52,  1],
       [49,  0],
       [52,  0],
       [67,  1],
       [52,  1],
       [54,  1],
       [49,  1],
       [58,  1],
       [39,  1],
       [70,  1],
       [47,  1],
       [51,  0],
       [54,  0],
       [58,  0],
       [62,  0],
       [66,  0],
       [61,  1],
       [63,  0],
       [64,  0],
       [45,  1],
       [60,  0],
       [39,  1],
       [65,  0],
       [48,  1],
       [44,  1],
       [66,  0],
       [65,  1],
       [58,  0],
       [47,  1],
       [45,  0],
       [55,  0],
       [35,  1],
       [59,  1],
       [60,  1],
       [55,  0],
       [53,  0],
       [63,  1],
       [70,  1],
       [51,  0],
       [63,  0],
       [58,  1],
       [56,  1],
       [68,  0],
       [44,  0],
       [37,  1],
       [53,  0],
       [41,  1],
       [52,  1],
       [51,  1],
       [57,  1],
       [62,  1],
       [54,  1],
       [59,  0],
       [64,  1],
       [54,  0],
       [67,  1],
       [59,  1],
       [41,  0],
       [61,  1

In [ ]:
x_test

array([[57,  1],
       [59,  1],
       [57,  1],
       [56,  0],
       [71,  0],
       [57,  1],
       [46,  0],
       [56,  0],
       [54,  1],
       [54,  1],
       [57,  1],
       [59,  1],
       [52,  1],
       [40,  1],
       [46,  0],
       [44,  1],
       [34,  0],
       [54,  1],
       [46,  1],
       [61,  1],
       [64,  1],
       [56,  1],
       [67,  1],
       [71,  0],
       [44,  0],
       [40,  1],
       [59,  1],
       [51,  1],
       [57,  1],
       [50,  0],
       [64,  1],
       [61,  1],
       [62,  1],
       [45,  1],
       [66,  0],
       [63,  1],
       [51,  1],
       [48,  1],
       [40,  1],
       [45,  1],
       [52,  1],
       [59,  1],
       [62,  1],
       [41,  1],
       [44,  1],
       [43,  1],
       [52,  1],
       [52,  1],
       [58,  0],
       [55,  1],
       [48,  1],
       [45,  1],
       [41,  1],
       [60,  0],
       [58,  1],
       [62,  0],
       [69,  1],
       [50,  1],
       [68,  1

In [ ]:
y_train

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1])

In [ ]:
y_test

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1])

NameError: ignored